<form method="post" 
action="<?=App::config('url')?>igrac/promjena/<?=$e->sifra?>">
<label for="ime">Ime igrača</label>
<input type="text" name="ime" id="ime" value="<?=$e->ime?>">
<label for="rings_count">broj prstenja</label>
<input type="text" name="rings_count" id="rings_count" value="<?=$e->rings_count?>">
<label for="prezime">Prezime igrača:</label>
<input type="text" name="prezime" id="prezime" value="<?=$e->prezime?>">

<label for="nba_team">Momčad</label>
<select name="nba_team" id="nba_team">
    <?php foreach($nba_teams as $n): ?>
        <option
        <?php if ($e->nba_team==$n->sifra){
            echo ' selected="selected"';
        }
        ?>
        value="<?=$n->sifra?>"><?=$n->$ime_kluba?></option>
    <?php endforeach; ?>
    </select>

<?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>igrac">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>

</form>



