<form method="post" 
action="<?=App::config('url')?>igrac/promjena/<?=$e->sifra?>">
<label for="naziv">Ime igrača</label>
<input type="text" name="ime" id="ime" value="<?=$e->ime?>">
<label for="naziv">broj prstenja</label>
<input type="text" name="rings_count" id="rings_count" value="<?=$e->rings_count?>">
<label for="naziv">Prezime igrača:</label>
<input type="text" name="prezime" id="prezime" value="<?=$e->prezime?>">
<label for="nba_team">Ekipa</label>
<select name="nba_team" id="nba_team">
    <?php foreach($nba_team as $n): ?>
        <option
        <?php if ($e->nba_team==$n->sifra){
            echo ' selected="selected"';
        }
        ?>
        value="<?=$s->sifra?>"><?=$s->ime?></option>
    <?php endforeach; ?>
</select>




<?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>igrac">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>

</form>



