<a href="<?=App::config('url')?>igrac/novi"
    class="success button expanded">Dodaj novi</a>
<div class="grid-x grid-padding-x">
    <?php foreach($entiteti as $e):?>
        <div class="large-3 cell">
            <div class="callout" style="text-align: center;">
                slika
                <hr />
                <h2 style="font-size: 1.5rem;"> <?=$e->ime?> <?=$e->prezime?></h2>
                   broj prstena: <?=$e->rings_count?>
                <h6>Ekipa:<?=$e->ime_kluba?></h6>
                <hr />
                <a href="<?=App::config('url')?>igrac/promjena/<?=$e->sifra?>">
                    <i style="color: blue;" 
                    class="step fi-pencil size-36"></i>
                </a>
                <a href="<?=App::config('url')?>igrac/brisanje/<?=$e->sifra?>">
                <i style="color: red;" 
                    class="step fi-trash size-36"></i>
            </a>
            </div>
        </div>
    <?php endforeach ?>
</div>