<a class="success button expanded" 
    href="<?=App::config('url')?>igrac/novi">
        Dodaj Novog igrača
</a>

<table>
    <thead>
        <tr>
            <th>Momčad</th>
            <th>ime</th>
            <th>prezime</th>
            <th>Broj pobjeda u finalu NBA</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $e): ?>
            <tr>
            <td><?=$e->ime_kluba?></td>
                <td><?=$e->ime?></td>
                <td><?=$e->prezime?></td>
                <td><?=$e->rings_count?></td>
                <td>
                    <div>
                    <a href="<?=App::config('url')?>igrac/promjena/<?=$e->sifra?>">
                            <i style="color: blue;" 
                            class="step fi-pencil size-36"></i>
                     </a>
                     </div>
                     <div>
                        <a href="<?=App::config('url')?>igrac/brisanje/<?=$e->sifra?>">
                            <i style="color: red;" 
                            class="step fi-page-delete size-36"></i>
                        </a>
                        </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
