<div class="media-object">
  <div class="media-object-section align-self-middle">
    <div class="thumbnail">
      <img src= "assets/img/media-object/avatar-2.jpg">
    </div>
  </div>
  <div class="media-object-section main-section">
    <h4>Why is it so important to dream?</h4>
    <p>So, once we've made the plant, how do we go out? Hope you have something more elegant in mind than shooting me in the head? A kick. What's a kick? This, Ariadne, would be a kick.</p>
    <p>What is the most resilient parasite? Bacteria? A virus? An intestinal worm? An idea. Resilient... highly contagious. Once an idea has taken hold of the brain it's almost impossible to eradicate. An idea that is fully formed - fully understood - that sticks; right in there somewhere.</p>
  </div>
  <div class="media-object-section align-self-bottom">
    <div class="thumbnail">
      <img src= "assets/img/media-object/avatar-3.jpg">
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th width="200">Škola</th>
      <th>Smjer</th>
      <th width="150">CEO</th>
      <th width="150">Founder</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Edunova</td>
      <td>PHP BACK-END DEVELOPER</td>
      <td>Filip Todorović</td>
      <td>Filip Todorović</td>
    </tr>
</table>