<div class="media-object">
  <div class="media-object-section align-self-middle">
    <div class="thumbnail">
      <img src= "assets/img/media-object/avatar-2.jpg">
    </div>
  </div>
  <div class="media-object-section main-section">
    <h4>Why is it so important to dream?</h4>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum </p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
  </div>
  <div class="media-object-section align-self-bottom">
    <div class="thumbnail">
      <img src= "assets/img/media-object/avatar-3.jpg">
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th width="200">Škola</th>
      <th>Smjer</th>
      <th width="150">CEO</th>
      <th width="150">Founder</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Edunova</td>
      <td>PHP BACK-END DEVELOPER</td>
      <td>Filip Todorović</td>
      <td>Filip Todorović</td>
    </tr>
</table>