<form method="post" 
action="<?=App::config('url')?>naruceni_proizvodi/promjena/<?=$e->sifra?>">
  
  
  <label>ime kupca
    <input type="text" name="ime" value="<?=$e->ime?>" required/>
  </label>

  <label>prezime kupca
    <input type="text" name="prezime" value="<?=$e->prezime?>" />
  </label>


  <label>e-mail
    <input type="email" name="email" value="<?=$e->email?>" />
  </label>

  <label>datum isporuke
    <input type="text" name="datum_isporuke" value="<?=$e->datum_isporuke?>" />
  </label>
  
  <label> ukupna tezina proizvoda u KG
    <input type="text" name="ukupna_tezina_proizvoda" value="<?=$e->ukupna_tezina_proizvoda?>" />
  </label>

    
  <label> ukupna cijena proizvoda u HRK
    <input type="text" name="ukupna_cijena_proizvoda" value="<?=$e->ukupna_cijena_proizvoda?>" />
  </label>

  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>naruceni_proizvodi">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>


</form>