<a class="success button expanded" 
    href="<?=App::config('url')?>kosarica/novi">
        Dodaj novu narudžbu 
</a>

<table>
    <thead>
        <tr>
            <th>ukupna težina proizvoda</th>
            <th>ukupna cijena proizvoda</th>
            <th>datum isporuke</th>
            <th>količina opreme</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $e): ?>
            <tr>
            <td><?=$e->ukupna_tezina_proizvoda?></td>
                <td><?=$e->ukupna_cijena_proizvoda?></td>
                <td><?=$e->datum_isporuke?></td>
                <td><?=$e->kolicina_opreme?></td>
                <td>
                    <div>
                    <a href="<?=App::config('url')?>kosarica/promjena/<?=$e->sifra?>">
                            <i style="color: blue;" 
                            class="step fi-pencil size-36"></i>
                     </a>
                     </div>
                     <div>
                        <a href="<?=App::config('url')?>kosarica/brisanje/<?=$e->sifra?>">
                            <i style="color: red;" 
                            class="step fi-page-delete size-36"></i>
                        </a>
                        </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>