<?php /* https://get.foundation/sites/docs/responsive-navigation.html#responsive-toggle */ ?>
<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?php  echo App::config('nazivApp');?></li>
      <li><a href="<?=App::config('url') ?>">Početna</a></li>
      <?php if(App::auth()): ?>
        <li><a href="<?=App::config('url') ?>nadzornaploca">Nadzorna ploča</a></li>
      <?php endif; ?>
    </ul>
  </div>
  <div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"></li>
      <li>
        <a href="#">Proizvodi</a>
        <ul class="menu vertical">
          <li><a href="<?=App::config('url') ?>proizvodi/dresovi">Dresovi</a></li>   <!-- URL treba popraviti kada napravim controler i view -->
          <li><a href="<?=App::config('url') ?>proizvodi/hlacice">Hlačice</a></li>   <!--  počinje od ovih linija -->
          <li><a href="<?=App::config('url') ?>proizvodi/patike">Patike</a></li>
          <li><a href="<?=App::config('url') ?>proizvodi/dodatna_oprema">Dodatna oprema</a></li>
        </ul>
      </li>
      <li><a href="<?=App::config('url') ?>onama/index">o nama</a></li>

    </ul>
  </div>
  <!-- <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
  </div> -->
</div>

  <div class="top-bar-right">
    <ul class="menu">
      <?php if(!App::auth()): ?>
        <li><a href="<?=App::config('url') ?>login/prijava">Prijava</a></li>
      <?php else: ?>
        <li><a href="<?=App::config('url') ?>login/odjava">Odjava 
      <?=App::user()->prezime?> <?=App::user()->ime?>
      </a></li>
      <?php endif; ?>
    </ul>
  </div>
</div>