<div class="grid-x grid-margin-x" id="tijelo">
      <div class="cell">
        <div class="callout" >
          
          <h1 id="naslov" style="text-align:center">All the legends in one place</h1>

        </div>
      </div>
    </div>
  <img class="cover" src="../public/img/legende1.png" alt="legende1" >
    <ul>
      <li>
        ovo je moj završni rad za školu Edunova. </br>
        na ovoj web stranici možete pronaći NBA proizvode vezane uz igrače i NBA timove
      </li>
    </ul>