<form method="post" 
action="<?=App::config('url')?>oprema/promjena/<?=$e->sifra?>">
  
  
  <label>velicina
    <input type="text" name="velicina" value="<?=$e->velicina?>" required/>
  </label>

  <label>Boja
    <input type="text" name="boja" value="<?=$e->boja?>" />
  </label>


  <label>cijena
    <input type="text" name="cijena" value="<?=$e->cijena?>" />
  </label>

  <label>tezina_proizvoda
    <input type="text" name="tezina_proizvoda" value="<?=$e->tezina_proizvoda?>" />
  </label>
  
  <label>vrsta_proizvoda
    <input type="text" name="vrsta_proizvoda" value="<?=$e->vrsta_proizvoda?>" />
  </label>

  <label for="igrac">igrač</label>
<select name="igrac" id="igrac">
    <?php foreach($igraci as $i): ?>
        <option
        <?php if ($e->igrac==$i->sifra){
            echo ' selected="selected"';
        }
        ?>
        value="<?=$i->sifra?>"><?=$i->ime?> <?=$i->prezime?></option>
    <?php endforeach; ?>
</select>

  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>oprema">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>


</form>