<i style="color:blueviolet" class="fi-like size-100"></i>
Programi-->kupac uspješno radi 
<i style="color:brown"  class="fi-like size-100"></i>
-->na Vps-u ne radi dobro, treba poboljšati i malo stilizirati još
<hr/>

<i style="color:palegreen"  class="fi-like size-100"></i>
Programi-->nba_team uspješno radi 
<i style="color:tomato"  class="fi-like size-100"></i>
-->na vps-u ne radi dobro, stil ok
<hr/>
krenio raditi igrača, ne radi mi ništa osim read funkcija(stao si u modelu igrač[create])