<i style="color:blueviolet" class="fi-like size-100"></i>
Programi-->kupac uspješno radi 
<i style="color:brown"  class="fi-like size-100"></i>
treba poboljšati i malo stilizirati još
<hr/>

<i style="color:palegreen"  class="fi-like size-100"></i>
Programi-->nba_team uspješno radi 
<i style="color:tomato"  class="fi-like size-100"></i>

<img  src="<?=App::config('url')?>../public/img/nba_shop.png" alt="">