<i style="color:blueviolet" class="fi-like size-100"></i>
Programi-->kupac uspješno radi 
<i style="color:brown"  class="fi-like size-100"></i>
treba poboljšati i malo stilizirati još
<hr/>

<i style="color:palegreen"  class="fi-like size-100"></i>
Programi-->nba_team uspješno radi 
<i style="color:tomato"  class="fi-like size-100"></i>
<hr/>
<h3>postavio ostalima read i create bez kontrola </h3>
<hr/>
<h4>promjena i delete i dalje ne rade</h4>
<hr/>