<div class="grid-x grid-padding-x">
    <?php foreach($entiteti as $e):?>
        <div class="large-3 cell">
            <div class="callout" style="text-align: center;">
                slika
                <hr />
                <h1 style="font-size: 1.5rem;"> <?=$e->ime_kluba?> <?=$e->championships_won?></h1>
                <?=$e->trener?> <?=$e->stadion?>
                <hr />
                <a href="<?=App::config('url')?>nba_team/promjena/<?=$e->sifra?>">
                    <i style="color: blue;" 
                    class="step fi-pencil size-36"></i>
                </a>
            </div>
        </div>
    <?php endforeach ?>
</div>